name: post-merge
on:
  pull_request:
    branches:
      - master
      - /\d\.0\.0-RC/
  workflow_dispatch:
jobs:
  tests-coverage:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set branch name and PR number
        id: refs
        env:
          BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
        run: |
          echo "::set-output name=branch_name::${BRANCH_NAME_OR_REF#refs/heads/}"
          echo "::set-output name=pr_number::$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
      - name: Coveralls Maven plugin
        env:
          CI_NAME: Github
          CI_BUILD_NUMBER: ${{ github.run_id }}
          CI_BUILD_URL: https://github.com/${{ github.repository }}/commit/${{ github.event.after }}/checks
          CI_BRANCH: ${{ steps.refs.outputs.branch_name }}
          CI_PULL_REQUEST: ${{ steps.refs.outputs.pr_number }}
          COVERALLS_REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          mvn verify javadoc:javadoc coveralls:report -Pcoverage -DrepoToken=${COVERALLS_REPO_TOKEN} -B -V
